// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlineFashionShopApp.Models;

public partial class AccessLog
{
    public int Id { get; set; }

    public string Action { get; set; }

    public DateTime ActionDate { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }
}