// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.VisualBasic.ApplicationServices;
using System;
using System.Collections.Generic;

namespace OnlineFashionShopApp.Models;

public partial class Shipment
{
    public int Id { get; set; }

    public string ShippingAddress1 { get; set; }

    public string ShippingAddress2 { get; set; }

    public string ShippingCountry { get; set; }

    public string ShippingCity { get; set; }

    public string ShippingState { get; set; }

    public string ShippingPostalCode { get; set; }

    public int UserId { get; set; }

    public virtual User User { get; set; }
}